services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  _instanceof:
    MwuSdk\Events\Listener\EventListenerInterface:
      tags: ['mwu_sdk.event_listener']

  MwuSdk\:
    resource: '../../'
    exclude:
      - '../../DependencyInjection/'
      - '../../Resources/'
      - '../../Entity/'
      - '../../Model'
      - '../../Enum'
      - '../../Builder'
      - '../../Dto'
      - '../../Exception'
      - '../../MwuSdkBundle.php'

  MwuSdk\Client\:
    resource: '../../Client/'
    exclude:
      - '../../Client/MwuLightModule'
      - '../../Client/MwuSwitch'
      - '../../Client/TcpIp'

  MwuSdk\Events\Manager\EventManager:
    $eventListeners: !tagged_iterator 'mwu_sdk.event_listener'
