services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  # Factories
  MwuSdk\:
    resource: '../../'
    exclude:
      - '../../DependencyInjection/'
      - '../../Resources/'
      - '../../Entity/'
      - '../../Model'
      - '../../Enum'
      - '../../Builder'
      - '../../Client'
      - '../../Dto'
      - '../../Exception'
      - '../../MwuSdkBundle.php'
