<?php

declare(strict_types=1);

namespace MwuSdk;

use MwuSdk\DependencyInjection\MwuSdkExtension;
use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\HttpKernel\Bundle\AbstractBundle;

class MwuSdkBundle extends AbstractBundle
{
    public function build(ContainerBuilder $container): void
    {
        parent::build($container); // TODO: Change the autogenerated stub

        $container->registerExtension(new MwuSdkExtension());
    }
}
